import { cssShortKeys, dynamic } from "../types";

export const cssProps : dynamic = {  
            
    "alignContent": "align-content",
    "alignItems": "align-items",
    "alignSelf": "align-self",
    
    //Animations
    "animation": "animation",
    "animationDelay": "animation-delay",
    "animationDirection": "animation-direction",
    "animationDuration": "animation-duration",
    "animationFillMode": "animation-fill-mode",
    "animationIterationCount": "animation-iteration-count",
    "animationName": "animation-name",
    "animationPlayState": "animation-play-state",
    "animationTimingFunction": "animation-timing-function",
    
    //Backgrounds
    "background": "background",
    "bg": "background",
    "backgroundColor": "background-color",
    "backgroundImage": "background-image",
    "bgi": "background-image",
    "bgc": "background-color",
    "backgroundOrigin": "background-origin",
    "backgroundPosition": "background-position",
    "backgroundRepeat": "background-repeat",
    "backgroundSize": "background-size",
    "backfaceVisibility": "backface-visibility",
    "backgroundAttachment": "background-attachment",
    "backgroundBlendMode": "background-blend-mode",
    "backgroundClip": "background-clip",
    "bg-clip": "background-clip",

    //Borders
    "border": "border",
    "borderBottom": "border-bottom",
    "borderBottomColor": "border-bottom-color",
    "borderBottomStyle": "border-bottom-style",
    "borderBottomWidth": "border-bottom-width",
    "borderCollapse": "border-collapse",
    "borderColor": "border-color",
    "borderImage": "border-image",
    "borderImageOutset": "border-image-outset",
    "borderImageRepeat": "border-image-repeat",
    "borderImageSlice": "border-image-slice",
    "borderImageSource": "border-image-source",
    "borderImageWidth": "border-image-width",
    "borderLeft": "border-left",
    "borderLeftColor": "border-left-color",
    "borderLeftStyle": "border-left-style",
    "borderLeftWidth": "border-left-width",
    "borderRight": "border-right",
    "borderRightColor": "border-right-color",
    "borderRightStyle": "border-right-style",
    "borderRightWidth": "border-right-width",
    "borderSpacing": "border-spacing",
    "borderStyle": "border-style",
    "borderTop": "border-top",
    "borderTopColor": "border-top-color",            
    "borderTopStyle": "border-top-style",
    "borderTopWidth": "border-top-width",
    "borderWidth": "border-width",
    
    //Radius
    "borderRadius": "border-radius",
    "r": "border-radius",
    "radius": "border-radius",
    "borderTopLeftRadius": "border-top-left-radius",
    "rtl": "border-top-left-radius",
    "borderTopRightRadius": "border-top-right-radius",
    "rtr": "border-top-right-radius",
    "borderBottomLeftRadius": "border-bottom-left-radius",
    "rbl": "border-bottom-left-radius",
    "borderBottomRightRadius": "border-bottom-right-radius",
    "rbr": "border-bottom-right-radius",

    
    "bottom": "bottom",
    "boxDecorationBreak": "box-decoration-break",
    "boxShadow": "box-shadow",
    "shadow": "box-shadow",
    "boxSizing": "box-sizing",
    "captionSide": "caption-side",
    "caretColor": "caret-color",
    "@charset": "@charset",
    "clear": "clear",
    "clip": "clip-path",
    "clipPath": "clip-path",
    "color": "color",
    "c": "color",
    "columnCount": "column-count",
    "columnFill": "column-fill",
    "columnGap": "column-gap",
    "colGap": "column-gap",
    "columnRule": "column-rule",
    "columnRuleColor": "column-rule-color",
    "columnRuleStyle": "column-rule-style",
    "columnRuleWidth": "column-rule-width",
    "columnSpan": "column-span",
    "columnWidth": "column-width",
    "columns": "columns",
    "content": "content",
    "counterIncrement": "counter-increment",
    "counterReset": "counter-reset",
    "cursor": "cursor",
    "pointer": "pointer",
    "direction": "direction",
    "display": "display",
    "emptyCells": "empty-cells",
    "filter": "filter",
    "flex": "flex",
    "flexBasis": "flex-basis",
    "flexDirection": "flex-direction",
    "flexDir": "flex-direction",
    "flexFlow": "flex-flow",
    "flexGrow": "flex-grow",
    "flexShrink": "flex-shrink",
    "shrink": "flex-shrink",
    "flexWrap": "flex-wrap",
    "float": "float",
    "font": "font",
    "fontFamily": "font-family",
    "fontKerning": "font-kerning",
    "s": "font-size",
    "fs": "font-size",
    "fontSize": "font-size",
    "fontSizeAdjust": "font-size-adjust",
    "fontStretch": "font-stretch",
    "fontStyle": "font-style",
    "fontVariant": "font-variant",
    "bold": "bold",
    "fontWeight": "font-weight",
    "b": "font-weight",
    "gap" : "gap",
    "grid": "grid",
    "gridArea": "grid-area",
    "gridAutoColumns": "grid-auto-columns",
    "gridAutoFlow": "grid-auto-flow",
    "gridAutoRows": "grid-auto-rows",
    "gridColumn": "grid-column",
    "gridColumnEnd": "grid-column-end",
    "gridColumnGap": "grid-column-gap",
    "gridColumnStart": "grid-column-start",
    "gridGap": "grid-gap",
    "gridRow": "grid-row",
    "gridRowEnd": "grid-row-end",
    "gridRowGap": "grid-row-gap",
    "gridRowStart": "grid-row-start",
    "gridTemplate": "grid-template",
    "gridTemplateAreas": "grid-template-areas",
    "grid-areas": "grid-template-areas",
    "gridTemplateColumns": "grid-template-columns",
    "grid-cols": "grid-template-columns",
    "gridTemplateRows": "grid-template-rows",
    "grid-rows": "grid-template-rows",
    "hangingPunctuation": "hanging-punctuation",
    "hyphens": "hyphens",
    "isolation": "isolation",
    "justifyContent": "justify-content",
    "left": "left",
    "letterSpacing": "letter-spacing",
    "spacing": "letter-spacing",
    "lineHeight": "line-height",
    "lh": "line-height",
    "listStyle": "list-style",
    "listStyleImage": "list-style-image",
    "listStylePosition": "list-style-position",
    "listStyleType": "list-style-type",
    "aspectRatio": "aspect-ratio",
    
    //Margin
    "margin": "margin",
    "m": "margin",
    "marginBottom": "margin-bottom",
    "mb": "margin-bottom",
    "marginLeft": "margin-left",
    "ml": "margin-left",
    "marginRight": "margin-right",
    "mr": "margin-right",
    "marginTop": "margin-top",
    "mt": "margin-top",
    
    //Height
    "height": "height",
    "h": "height",
    "minHeight": "min-height",
    "minH": "min-height",
    "maxHeight": "max-height",
    "maxH": "max-height",
    
    //Width
    "width": "width",
    "w": "width",
    "minWidth": "min-width",
    "minW": "min-width",
    "maxWidth": "max-width",
    "maxW": "max-width",
    
    "mixBlendMode": "mix-blend-mode",
    "objectFit": "object-fit",
    "fit": "object-fit",
    "objectPosition": "object-position",
    "opacity": "opacity",
    "order": "order",
    "outline": "outline",
    "outlineColor": "outline-color",
    "outlineOffset": "outline-offset",
    "outlineStyle": "outline-style",
    "outlineWidth": "outline-width",
    "overflow": "overflow",
    "overflowX": "overflow-x",
    "overflowY": "overflow-y",
    

    "padding": "padding",
    "p": "padding",
    "paddingBottom": "padding-bottom",
    "pb": "padding-bottom",
    "paddingLeft": "padding-left",
    "pl": "padding-left",
    "paddingRight": "padding-right",
    "pr": "padding-right",
    "paddingTop": "padding-top",
    "pt": "padding-top",
    
    "pageBreakAfter": "page-break-after",
    "pageBreakBefore": "page-break-before",
    "pageBreakInside": "page-break-inside",
    "perspective": "perspective",
    "perspectiveOrigin": "perspective-origin",
    "pointerEvents": "pointer-events",
    
    "position": "position",
    
    "quotes": "quotes",
    "resize": "resize",
    "right": "right",
    "scrollBehavior": "scroll-behavior",
    "tabSize": "tab-size",
    "tableLayout": "table-layout",
    
    "align" : "text-align",
    "textAlign": "text-align",
    "textAlignLast": "text-align-last",
    
    "textDecoration": "text-decoration",
    "td": "text-decoration",
    "textDecorationColor": "text-decoration-color",
    "textDecorationLine": "text-decoration-line",
    "textDecorationStyle": "text-decoration-style",
    "textIndent": "text-indent",
    "textJustify": "text-justify",
    "textOverflow": "text-overflow",
    "textShadow": "text-shadow",
    "textTransform": "text-transform",
    "textStroke": "-webkit-text-stroke",
    "top": "top",
    
    "transform": "transform",
    "transform(2D)": "transform(2D)",
    "transformOrigin": "transform-origin",
    "origin": "transform-origin",
    "transformStyle": "transform-style",
    "transition": "transition",
    "transitionDelay": "transition-delay",
    "transitionDuration": "transition-duration",
    "transitionProperty": "transition-property",
    "transitionTimingFunction": "transition-timing-function",
    "unicodeBidi": "unicode-bidi",
    "userSelect": "user-select",
    "verticalAlign": "vertical-align",
    "visibility": "visibility",
    
    "whiteSpace": "white-space",
    "wordBreak": "word-break",
    "wordSpacing": "word-spacing",
    "textWrap": "textWrap",
    "wordWrap": "word-wrap",
    "writingMode": "writing-mode",
    "zIndex": "z-index",
    "backdropFilter": "backdrop-filter",

    "placeItems": "place-items",
    "placeContent": "place-content",

    "corner": "corner-shape",

    "ph": "padding-left:__VALUE__;padding-right:__VALUE__;",
    "pv": "padding-top:__VALUE__;padding-bottom:__VALUE__;",
    "mh": "margin-left:__VALUE__;margin-right:__VALUE__;",
    "mv": "margin-top:__VALUE__;margin-bottom:__VALUE__;",
    "translate": "translate: __VALUE__;",
    "translateX": "translate: __VALUE__ 0px 0px;",
    "translateY": "translate: 0px __VALUE__ 0px;",
    "translateZ": "translate: 0px 0px __VALUE__;",
    "x": "translate: __VALUE__ 0px 0px;",
    "y": "translate: 0px __VALUE__ 0px;",
    "z": "translate: 0px 0px __VALUE__;",
    "rotate": "rotate: __VALUE__;",
    "rotateX": "rotate: 1 0 0 __VALUE__;",
    "rotateY": "rotate: 0 1 0 __VALUE__;",
    "rotateZ": "rotate: 0 0 1 __VALUE__;",
    "rotate3d": "rotate: 1 1 1 __VALUE__;",
    "scale": "scale: __VALUE__;",
    "view": "perspective: __VALUE__;",
    "anim": "transition: all __VALUE__ __CURVE__ __DELAY__;",
    "blur" : "filter: blur(__VALUE__);",
    "saturate" : "filter: saturate(__VALUE__);",
    "brightness" : "filter: brightness(__VALUE__);",
    "ratio" : "aspect-ratio: __VALUE__;",
    "extend": "@extend __VALUE__;",
    "keyframes": "animation: __NAME__ __DURATION__ __CURVE__ __ITERATIONS__;",
    "play": "animation: __NAME__ __DURATION__ __CURVE__ __ITERATIONS__;",
}

export const cssDirect : dynamic = {
    "content": "content:'';",
    "bold": "font-weight: bold;",
    "grid": "display:grid;",
    "flex": "display:flex;",
    "flex-1": "flex:1;",
    "flex-2": "flex:2;",
    "flex-3": "flex:3;",
    "wrap": "flex-wrap:wrap;",
    "cols": "flex-direction:column;",
    "cols-reverse": "flex-direction:column-reverse;",
    "cols-rev": "flex-direction:column-reverse;",
    "ass": "align-self:flex-start;",
    "ais": "align-items:flex-start;",
    "aib": "align-items:baseline;",
    "aic": "align-items:center;",
    "align-items-center": "align-items:center;",
    "aie": "align-items:flex-end;",
    "jcs": "justify-content:flex-start;",
    "jcc": "justify-content:center;",
    "jce": "justify-content:flex-end;",
    "jcb": "justify-content:space-between;",
    "jca": "justify-content:space-around;",
    "pis": "place-items:start",
    "pie": "place-items:end",
    "pic": "place-items:center",
    "pist": "place-items:stretch",
    "pcs": "place-content:start",
    "pcc": "place-content:center",
    "pce": "place-content:end",
    "pcst": "place-content:stretch",
    "tal": "text-align: left;",
    "tac": "text-align: center;",
    "tar": "text-align: right;",
    "tas": "text-align: justify;",
    "fill": "top: 0px;left: 0px;right: 0px;bottom: 0px;",
    "rel": "position:relative;",
    "abs": "position:absolute;",
    "fixed": "position:fixed;",
    "sticky": "position:sticky;",
    "abc": "top:50%;left:50%;--abc-x:-50%;--abc-y:-50%;translate:calc(var(--abc-x) + var(--fx-x, 0px) + var(--fx-enter-x, 0px)) calc(var(--abc-y) + var(--fx-y, 0px) + var(--fx-enter-y, 0px));",
    "tdn": "text-decoration:none;",
    "tdu": "text-decoration:underline;",
    "nous": "user-select:none;",
    "nope": "pointer-events:none;",
    "pe-none": "pointer-events:none;",
    "pe-auto": "pointer-events:auto;",
    "3d": "transform-style: preserve-3d;",
    "hide" : "display: none;",
    "block" : "display: block;",
    "inlineblock" : "display: inline-block;",
    "center-h": "left: 50%;--abc-x: -50%;translate: calc(var(--abc-x) + var(--fx-x, 0px) + var(--fx-enter-x, 0px)) calc(var(--fx-y, 0px) + var(--fx-enter-y, 0px));",
    "center-x": "left: 50%;--abc-x: -50%;translate: calc(var(--abc-x) + var(--fx-x, 0px) + var(--fx-enter-x, 0px)) calc(var(--fx-y, 0px) + var(--fx-enter-y, 0px));",
    "center-v": "top: 50%;--abc-y: -50%;translate: calc(var(--fx-x, 0px) + var(--fx-enter-x, 0px)) calc(var(--abc-y) + var(--fx-y, 0px) + var(--fx-enter-y, 0px));",
    "center-y": "top: 50%;--abc-y: -50%;translate: calc(var(--fx-x, 0px) + var(--fx-enter-x, 0px)) calc(var(--abc-y) + var(--fx-y, 0px) + var(--fx-enter-y, 0px));",
    "no-overflow": "overflow: hidden;",
    "no-overflow-x": "overflow-x: hidden;",
    "no-overflow-y": "overflow-y: hidden;",
    "overflow-x": "overflow-x: auto;",
    "overflow-y": "overflow-y: auto;",
    "scroll-x": "overflow-x: auto;",
    "scroll-y": "overflow-y: auto;",
    "space-pre": "white-space: pre;",
    "white-space-pre": "white-space: pre;",
    "text-wrap": "width: 98%;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;",
    "text-clip": "color: transparent;background-clip: text;-webkit-background-clip: text;",
    "word-break": "word-break: break-word;",
    "uppercase": "text-transform: uppercase;",
    "lowercase": "text-transform: lowercase;",
    "capitalize": "text-transform: capitalize;",
    "italic": "font-style: italic;",
    //Ratio
    "ratio-square": "aspect-ratio: 1 / 1;",
    "ratio-video": "aspect-ratio: 16 / 9;",
    "ratio-monitor": "aspect-ratio: 21 / 9;",
    "ratio-photo": "aspect-ratio: 4 / 3;",
    "ratio-portrait": "aspect-ratio: 3 / 4;",
    "ratio-tall": "aspect-ratio: 9 / 16;",
    //
    "backdrop-blur": "backdrop-filter: blur(10px);",
    "backdrop-blur-sm": "backdrop-filter: blur(4px);",
    "backdrop-blur-md": "backdrop-filter: blur(8px);",
    "backdrop-blur-lg": "backdrop-filter: blur(12px);",
    "backdrop-blur-xl": "backdrop-filter: blur(16px);",
    "backdrop-blur-xxl": "backdrop-filter: blur(24px);",
    "backdrop-blur-2xl": "backdrop-filter: blur(24px);",
}

export const cssPropsWithColor = [
    // Regular CSS keys
    "color",
    "bg",
    "background",
    "background-color",
    "border",
    "border-color",
    "border-top-color",
    "border-right-color",
    "border-bottom-color",
    "border-left-color",
    "outline-color",
    "text-decoration-color",
    "text-shadow",
    "box-shadow",
    "fill",
    "stroke",
    "stop-color",
    "caret-color",
    "column-rule-color",
    "text-emphasis-color",
    "accent-color",
    "border-block-color",
    "border-inline-color",
    "column-fill",
    "marker",
    "scrollbar-color",
    "outline-offset-color",
  
    // JSX camelCase keys
    "backgroundColor",
    "borderColor",
    "borderTopColor",
    "borderRightColor",
    "borderBottomColor",
    "borderLeftColor",
    "outlineColor",
    "textDecorationColor",
    "textShadow",
    "boxShadow",
    "fill",
    "stroke",
    "stopColor",
    "caretColor",
    "columnRuleColor",
    "textEmphasisColor",
    "accentColor",
    "borderBlockColor",
    "borderInlineColor",
    "columnFill",
    "marker",
    "scrollbarColor",
    "outlineOffsetColor",
]

export const cssAnimationCurves : dynamic = {
    ease: 'ease',
    in: 'ease-in',
    out: 'ease-out',
    inout: 'ease-in-out',
    linear: 'linear',
    start: 'step-start',
    end: 'step-end',
    steps: 'steps',
    cubic: 'cubic-bezier',
    initial: 'initial',
    inherit: 'inherit'
}

export const cssAnimationFunctions : dynamic = {
    animation: 'animation',
    name: 'animation-name',
    duration: 'animation-duration',
    timing: 'animation-timing-function',
    delay: 'animation-delay',
    count: 'animation-iteration-count',
    direction: 'animation-direction',
    fill: 'animation-fill-mode',
    state: 'animation-play-state',
    frames: 'keyframes'
}

export const cssTransformKeys: string[] = [
    'translate',
    'translateX',
    'translateY',
    'translateZ',
    'scale',
    'scaleX',
    'scaleY',
    'scaleZ',
    'rotate',
    'rotateX',
    'rotateY',
    'rotateZ',
    'skew',
    'skewX',
    'skewY',
    'perspective',
    'matrix',
    'matrix3d',
];

export const cssFilterKeys: string[] = [
    'blur',
    'brightness',
    'contrast',
    'drop-shadow',
    'grayscale',
    'hue-rotate',
    'invert',
    'saturate',
    'sepia',
];

export const cssWithKeys : cssShortKeys = {
    w: `width`,
    minW: `minWidth`,
    maxW: `maxWidth`,
    h: `height`,
    minH: `minHeight`,
    maxH: `maxHeight`,
    x: `translateX`,
    y: `translateY`,
    z: `translateZ`,
    r: `rotate`,
    rx: `rotateX`,
    ry: `rotateY`,
    rz: `rotateZ`,
    s: `scale`,
    sx: `scaleX`,
    sy: `scaleY`,
    sz: `scaleZ`,
}